# Include shared configurations from the config.d directory
include = ["./config.d/*.toml"]

# You can add specific overrides or additional configurations below if needed.
# For example:
# [llm]
# provider = "openai" # Override provider if necessary

# Specific settings for a file not covered by includes:
# [docs."SPECIAL_FILE.md"]
# title = "Special Document Title"
# purpose = "Specific purpose for this file"
# target = "Specific audience"
