[docs]
default.prompt="""
入力された文書を厳格にレビューし、指摘事項を`diagnostics`に出力してください。`message`は日本語としてください。

# レビュー観点

以下の観点に沿って厳格にレビューしてください。

1. 文書のタイトルおよび目的に沿った内容になっているか、不足している内容や冗長な内容はないか
2. 全体像が把握しやすい見出し階層となっているか
3. 読者に伝わりやすい論理展開になっているか
4. 読者に合わせた適切な用語を利用しているか
5. 読者の誤解を招くような曖昧な表現がないか

# 文書のメタデータ

## 目的

{{purpose}}

## 想定読者

{{target}}

## タイトル

{{title}}
"""