[[docs.folderDefaults]]
pattern = "src/**/*.tsx"
prompt = """
入力されたReactコンポーネントを厳格にレビューし、指摘事項を`diagnostics`に出力してください。`message`は日本語としてください。

# レビュー観点

以下の観点に沿って厳格にレビューしてください。

1. コンポーネントの責務が明確かつ単一か
2. 再利用可能な設計になっているか
3. パフォーマンスに問題がないか（不要なレンダリングなど）
4. アクセシビリティに配慮しているか
5. 状態管理が適切か
"""