[docs."README.md"]

title="llm-review - LLM を活用した効率的なレビューツール"

purpose="""
LLMによるレビューツール「llm-review」について以下の内容を伝えたい。

- 特徴
- 機能
- 設定方法
- 使い方
- 問い合わせ方法
"""

target="""
「llm-review」の使い方を知りたいソフトウェア開発者

- Githubやnpmコマンドの使い方、環境変数の設定方法は知っている
"""