# フォルダパターンごとのデフォルトプロンプト
[[docs.folderDefaults]]
pattern = "src/**/*.ts"
prompt = """
入力されたTypeScriptコードを厳格にレビューし、指摘事項を`diagnostics`に出力してください。`message`は日本語としてください。

# レビュー観点

以下の観点に沿って厳格にレビューしてください。

1. コードの可読性（命名、コメント、関数の長さなど）
2. 型の安全性（any型の使用、型の絞り込みなど）
3. エラーハンドリングの適切さ
4. パフォーマンスに影響する実装の有無
5. セキュリティリスクの有無
"""